package backofficedb

import (
	api "github.com/mateusmoutinho/churrasco/sandbox/api"
	database "github.com/mateusmoutinho/churrasco/sandbox/deps/database"
)

// New builds the backofficedb database from the Props its specs.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a handle over a prefix, so building one creates nothing until the first
// record is written.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *Backofficedb {
	props := database.Props{
		Path: "backofficedb",
		Schemas: []database.Schema{
			{
				Name: "backofficeuser",
				Itens: []database.Item{
					{Name: "username", Type: database.String, Required: true},
					{Name: "email", Type: database.String, Required: true},
					{Name: "passwordhash", Type: database.String, Required: true},
					{Name: "role", Type: database.Int},
					{Name: "sessions", Type: database.Database, Itens: []database.Item{
						{Name: "expiresat", Type: database.Int, Required: true}}},
				},
			},
			{
				Name: "apitoken",
				Itens: []database.Item{
					{Name: "tokensha", Type: database.Key, Required: true},
					{Name: "name", Type: database.String, Required: true},
					{Name: "prefix", Type: database.String, Required: true},
					{Name: "ownerid", Type: database.Int},
					{Name: "createdat", Type: database.Int},
					{Name: "expiresat", Type: database.Int},
					{Name: "ips", Type: database.String},
					{Name: "lastusedat", Type: database.Int},
					{Name: "lastusedip", Type: database.String},
				},
			},
		},
	}

	self := Backofficedb{sandbox: sandbox}
	self.handle = sandbox.Deps.Database.Databases.New(props)

	self.AddBackofficeuser = func(props BackofficeuserNew) (BackofficeuserItem, error) {
		return AddBackofficeuser(self.sandbox, &self, props)
	}
	self.FindBackofficeuserById = func(id int64) (BackofficeuserItem, bool) {
		return FindBackofficeuserById(self.sandbox, &self, id)
	}
	self.ListBackofficeuser = func(filtrage BackofficeuserFiltrage) ([]BackofficeuserItem, error) {
		return ListBackofficeuser(self.sandbox, &self, filtrage)
	}
	self.PageBackofficeuser = func(position int, chunk int) ([]BackofficeuserItem, error) {
		return PageBackofficeuser(self.sandbox, &self, position, chunk)
	}
	self.CountBackofficeuser = func() (int, error) {
		return CountBackofficeuser(self.sandbox, &self)
	}
	self.UpdateBackofficeuserUsername = func(id int64, value string) error {
		return UpdateBackofficeuserUsername(self.sandbox, &self, id, value)
	}
	self.UpdateBackofficeuserEmail = func(id int64, value string) error {
		return UpdateBackofficeuserEmail(self.sandbox, &self, id, value)
	}
	self.UpdateBackofficeuserPasswordhash = func(id int64, value string) error {
		return UpdateBackofficeuserPasswordhash(self.sandbox, &self, id, value)
	}
	self.UpdateBackofficeuserRole = func(id int64, value int64) error {
		return UpdateBackofficeuserRole(self.sandbox, &self, id, value)
	}
	self.RemoveBackofficeuser = func(id int64) error {
		return RemoveBackofficeuser(self.sandbox, &self, id)
	}
	self.AddBackofficeuserSessions = func(parent_id int64, props SessionsNew) (SessionsItem, error) {
		return AddBackofficeuserSessions(self.sandbox, &self, parent_id, props)
	}
	self.ListBackofficeuserSessions = func(parent_id int64) ([]SessionsItem, error) {
		return ListBackofficeuserSessions(self.sandbox, &self, parent_id)
	}
	self.AddApitoken = func(props ApitokenNew) (ApitokenItem, error) {
		return AddApitoken(self.sandbox, &self, props)
	}
	self.FindApitokenById = func(id int64) (ApitokenItem, bool) {
		return FindApitokenById(self.sandbox, &self, id)
	}
	self.FindApitokenByTokensha = func(value string) (ApitokenItem, bool) {
		return FindApitokenByTokensha(self.sandbox, &self, value)
	}
	self.ListApitoken = func(filtrage ApitokenFiltrage) ([]ApitokenItem, error) {
		return ListApitoken(self.sandbox, &self, filtrage)
	}
	self.PageApitoken = func(position int, chunk int) ([]ApitokenItem, error) {
		return PageApitoken(self.sandbox, &self, position, chunk)
	}
	self.CountApitoken = func() (int, error) {
		return CountApitoken(self.sandbox, &self)
	}
	self.UpdateApitokenTokensha = func(id int64, value string) error {
		return UpdateApitokenTokensha(self.sandbox, &self, id, value)
	}
	self.UpdateApitokenName = func(id int64, value string) error {
		return UpdateApitokenName(self.sandbox, &self, id, value)
	}
	self.UpdateApitokenPrefix = func(id int64, value string) error {
		return UpdateApitokenPrefix(self.sandbox, &self, id, value)
	}
	self.UpdateApitokenOwnerid = func(id int64, value int64) error {
		return UpdateApitokenOwnerid(self.sandbox, &self, id, value)
	}
	self.UpdateApitokenCreatedat = func(id int64, value int64) error {
		return UpdateApitokenCreatedat(self.sandbox, &self, id, value)
	}
	self.UpdateApitokenExpiresat = func(id int64, value int64) error {
		return UpdateApitokenExpiresat(self.sandbox, &self, id, value)
	}
	self.UpdateApitokenIps = func(id int64, value string) error {
		return UpdateApitokenIps(self.sandbox, &self, id, value)
	}
	self.UpdateApitokenLastusedat = func(id int64, value int64) error {
		return UpdateApitokenLastusedat(self.sandbox, &self, id, value)
	}
	self.UpdateApitokenLastusedip = func(id int64, value string) error {
		return UpdateApitokenLastusedip(self.sandbox, &self, id, value)
	}
	self.RemoveApitoken = func(id int64) error {
		return RemoveApitoken(self.sandbox, &self, id)
	}

	return &self
}
