package list_backoffice_users

// Entries is every value this route reads off a request, one field per entry
// of its route.yaml: FullRoute, the whole request path, then one per entry of
// `paths` and one per entry of `parameters`, then Body when the route declares
// one, each tagged with the id the generic RequestHandler fills it by. InternalPureHandler is handed
// one, already filled.
// Generated by `agnos build` — do not edit by hand.
type Entries struct {
	FullRoute                string `id:"FullRoute"`
	AdminListBackofficeUsers string `id:"AdminListBackofficeUsers"`
	Search                   string `id:"Search"`
	Role                     string `id:"Role"`
	Page                     int    `id:"Page"`
	Limit                    int    `id:"Limit"`
	Notice                   string `id:"Notice"`
}
