package list_backoffice_users

import (
	"github.com/mateusmoutinho/churrasco/sandbox/api"
	"github.com/mateusmoutinho/churrasco/sandbox/deps/serverdeps"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/generated/server/route"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/generated/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "list_backoffice_users"
	self.AcceptMethods = []string{"GET"}
	self.Priority = 100
	self.ResponseType = "text/html"
	self.Segments = 2
	self.Pattern = "/admin/list-backoffice-users"
	self.Category = "Backoffice Users"
	self.Help = "Lists backoffice users, filtered and paginated"
	self.LongDescription = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "AdminListBackofficeUsers",
			Start:       0,
			End:         1,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "/admin/list-backoffice-users", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "Search",
			Key:         "search",
			Fonts:       []api.ParameterFont{api.QueryParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "matches the username or the email, case-insensitive",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Role",
			Key:         "role",
			Fonts:       []api.ParameterFont{api.QueryParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "root, viewer, or empty for every role",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Page",
			Key:         "page",
			Fonts:       []api.ParameterFont{api.QueryParam},
			Required:    false,
			Type:        api.IntegerType,
			Default:     "1",
			HasDefault:  true,
			Description: "the page to show, counted from 1",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Limit",
			Key:         "limit",
			Fonts:       []api.ParameterFont{api.QueryParam},
			Required:    false,
			Type:        api.IntegerType,
			Default:     "20",
			HasDefault:  true,
			Description: "how many users a page shows, from 1 to 100",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "Notice",
			Key:         "notice",
			Fonts:       []api.ParameterFont{api.QueryParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the outcome code of the last add, edit or remove",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
