package commandprops

// CommandProps is what one command line carries from the commands that run on
// it to the ones after them: the dispatch builds one, empty, per command line,
// and hands the same one to every InternalPureHandler of the chain as its
// first argument. A middleware that parsed a --path or a --profile sets it
// here, and the command it runs in front of reads it.
//
// It embeds every struct declared by the other files of this package, so each
// of their fields is read as props.<Field>: project.go is the project's own,
// and a mechanic that hands something on adds a file of its own beside it.
// Two parts may not declare the same field; `agnos verify` says
// which.
//
// Generated by `agnos build` — do not edit by hand: declare a
// field in project.go, or in a file of your own in this package.
type CommandProps struct {
	Project
}
