package routeprops

// RouteProps is what one request carries from route to route of its chain: the
// dispatch builds one, empty, per request and hands the same one to every
// InternalPureHandler that runs for it, as its first argument. A middleware
// sets what it learned — the user it authenticated — and every route after it
// reads it, typed.
//
// It embeds every struct declared by the other files of this package, so each
// of their fields is read as props.<Field>: project.go is the project's own,
// and a mechanic that hands something on adds a file of its own beside it.
// Two parts may not declare the same field; `agnos verify` says
// which.
//
// Generated by `agnos build` — do not edit by hand: declare a
// field in project.go, or in a file of your own in this package.
type RouteProps struct {
	Backoffice
	Project
}
