package create_backoffice_api_token

import (
	"github.com/mateusmoutinho/churrasco/sandbox/api"
	"github.com/mateusmoutinho/churrasco/sandbox/deps/serverdeps"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/generated/server/route"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/generated/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "create_backoffice_api_token"
	self.AcceptMethods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "text/html"
	self.Segments = 2
	self.Pattern = "/admin/create-backoffice-api-token"
	self.Category = "Backoffice API Tokens"
	self.Help = "Creates an API token and shows it once"
	self.LongDescription = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "AdminCreateBackofficeApiToken",
			Start:       0,
			End:         1,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "/admin/create-backoffice-api-token", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "form",
		Required:    true,
		MaxBytes:    1048576,
		ContentType: "application/x-www-form-urlencoded",
		Schema:      BodySchema,
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
