package api_root_guard

import (
	"github.com/mateusmoutinho/churrasco/sandbox/api"
	"github.com/mateusmoutinho/churrasco/sandbox/deps/serverdeps"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/generated/server/route"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/generated/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "api_root_guard"
	self.AcceptMethods = []string{"ANY"}
	self.Priority = 11
	self.ResponseType = "application/json"
	self.Segments = 0
	self.Pattern = "/api/admin/root/*"
	self.Category = "Middleware"
	self.Help = "Lets only root users reach /api/admin/root"
	self.LongDescription = "Runs after api-authentication. A root user goes through; any other backoffice user is answered 403 in JSON."
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Route",
			Start:       0,
			End:         -1,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.PrefixTrigger, Value: "/api/admin/root", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
