package api_get_backoffice_user

import (
	"github.com/mateusmoutinho/churrasco/sandbox/api"
	serializables "github.com/mateusmoutinho/churrasco/sandbox/deps/serializables"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/generated/routeio"
)

// Entries is every value this route reads off a request, one field per entry
// of its route.yaml: FullRoute, the whole request path, then one per entry of
// `paths` and one per entry of `parameters`, then Body when the route declares
// one, each tagged with the id the generic RequestHandler fills it by. InternalPureHandler is handed
// one, already filled.
// Generated by `agnos build` — do not edit by hand.
type Entries struct {
	FullRoute                 string `id:"FullRoute"`
	ApiAdminGetBackofficeUser string `id:"ApiAdminGetBackofficeUser"`
	Body                      Body   `id:"Body"`
}

// Body is one object of this route's declared json-schema, as the
// generated ReadBody hands it over.
type Body struct {
	Id int
}

// MaxBodyBytes is the largest request body this route reads, from the
// `max-bytes` of its declaration. A longer one is answered 413.
const MaxBodyBytes = 1048576

// BodySchema is this route's declared json-schema in canonical form — the text
// routeio.ValidateSchema checks a request body against.
const BodySchema = "{\"properties\":{\"id\":{\"type\":\"integer\"}},\"required\":[\"id\"],\"type\":\"object\"}"

// ReadBody reads, validates and converts the request body of one bound route.
// The generic RequestHandler calls it — through the ReadBody new.go closes over
// the sandbox — before InternalPureHandler runs, and binds what it returns onto
// Entries.Body; a middleware in front of this route may still refuse a request
// before a byte of it is read.
//
// It returns nil when the body passed. Any other failure has already been
// answered — by this project's own HandleBadRequest or HandleTooLarge, which
// routeio.Raise hands it to — and the handler never runs.
func ReadBody(sandbox *api.Sandbox, route *api.Route) (Body, error) {
	var body Body

	raw, err := routeio.RequestOf(route).ReadBody(MaxBodyBytes)
	if err != nil {
		return body, routeio.RaiseWithCause(sandbox, route, api.StatusPayloadTooLarge, "",
			"the request body is larger than 1048576 bytes", err.Error())
	}

	if len(raw) == 0 {
		return body, routeio.Raise(sandbox, route, api.StatusBadRequest, "",
			"this route requires a request body")
	}

	parsed, field, message, ok := routeio.ValidateSchema(sandbox, BodySchema, raw)
	if !ok {
		return body, routeio.Raise(sandbox, route, api.StatusBadRequest, field, message)
	}

	body = bindBody(parsed)

	return body, nil
}

// bindBody converts one already-validated document into Body. The
// schema has been enforced by then, so a property that will not read was
// optional and comes back as its zero value.
func bindBody(document *serializables.SerializibleObject) Body {
	value := Body{}
	value.Id = routeio.ReadInt(document, "id")
	return value
}
