package add_backoffice_user

import (
	"github.com/mateusmoutinho/churrasco/sandbox/api"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/commandprops"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/generated/cli/command"
)

// NewCommand builds this command's declaration — a 1:1 image of its
// command.yaml — on the generic base of sandbox/internal/generated/cli/command,
// and closes InternalPureHandler over the sandbox as the handler behind it. It
// is called once by sandbox/internal/generated/cli/cli/new.go, and what it
// returns is one entry of Cli.Commands: the declaration alone, which the
// dispatch copies with api.BindCommand before binding a command line onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewCommand(sandbox *api.Sandbox) *api.Command {
	self := command.NewCommand(sandbox)

	self.Name = "add_backoffice_user"
	self.Identifiers = []string{"add-backoffice-user"}
	self.Priority = 100
	self.Segments = 0
	self.Strict = true
	self.Pattern = "add-backoffice-user"
	self.Category = "Backoffice"
	self.Help = "Creates a backoffice user with a generated password, printed once"
	self.LongDescription = "Adds a backoffice user under the same rules as the add form: the username and the email unique across both, regardless of case, and a valid email. The password is generated and printed once, so it never travels on the command line; change it on the edit page. --role defaults to viewer: give the first user --role root."
	self.Examples = []string{"add-backoffice-user --username admin --email admin@example.com --role root"}
	self.Hidden = false

	self.Args = []api.CommandArg{
		{
			Id:          "Command",
			Start:       0,
			End:         0,
			Type:        api.StringArg,
			Required:    false,
			Default:     "",
			HasDefault:  false,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "add-backoffice-user", Negate: false, IgnoreCase: false},
		},
	}

	self.Flags = []api.CommandFlag{
		{
			Id:          "Username",
			Keys:        []string{"--username"},
			Type:        api.StringFlag,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the username for the backoffice user",
		},
		{
			Id:          "Email",
			Keys:        []string{"--email"},
			Type:        api.StringFlag,
			Required:    true,
			Default:     "",
			HasDefault:  false,
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the email for the backoffice user",
		},
		{
			Id:          "Role",
			Keys:        []string{"--role"},
			Type:        api.StringFlag,
			Required:    false,
			Default:     "viewer",
			HasDefault:  true,
			Enum:        []string{"root", "viewer"},
			Pattern:     "",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
			Description: "the role of the backoffice user: root manages every user, viewer only reads",
		},
	}

	self.InternalPureHandler = func(props *commandprops.CommandProps, entries *Entries, response *api.CommandResponse) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
