package api

// Cli is the CLI surface of the sandbox: every command the project declares,
// and the dispatch that reads a command line against them. It is built by
// sandbox/internal/generated/cli/cli/new.go, generated by `agnos build`.
type Cli struct {
	// CliMain is the generated dispatch-and-parse entry point (see
	// sandbox/internal/generated/cli/cli/climain.go). It returns the exit
	// status the command line was answered with.
	CliMain func(args []string) int
	// Commands is every command the project declares, in run order —
	// lowest `priority` first, then by name — each built by the generated
	// NewCommand of its own package. The dispatch reads the command line
	// against these declarations; a caller holding the sandbox reads the
	// same surface without one.
	Commands []*Command
	// Fail answers one failure with the project's own handler for it: it
	// reads command.Failure and calls the matching Handle* of
	// sandbox/internal/cli/errors/. It is a field rather than a call because
	// a command package may not import sandbox/internal/generated/cli/cli —
	// that package imports every command. Raise a failure through
	// cliio.Raise — or, from a handler, return one built by cliio.Fail —
	// rather than calling this directly.
	Fail func(command *Command) error
}

const (
	// ExitOk reports that the command did what it was asked to do.
	ExitOk = 0
	// ExitFailure reports that a well-formed command could not be carried
	// out.
	ExitFailure = 1
	// ExitUsage reports that the command line itself was wrong — an unknown
	// command or flag, a missing operand, an unparsable amount. Every such
	// error exits with this one code, whichever command produced it.
	ExitUsage = 2
)
