package api

// Server is the http surface of the sandbox: every route the project declares,
// and the dispatch that reads a request against them. It is built by
// sandbox/internal/generated/server/server/new.go, generated by `agnos build`.
type Server struct {
	// Serve is the generated route-and-dispatch entry point (see
	// sandbox/internal/generated/server/server/servermain.go). It blocks until the
	// server stops.
	Serve func(props ServeProps) error
	// Routes is every http route the project declares, in run order —
	// lowest `priority` first, then by name — each built by the generated
	// NewRoute of its own package. The dispatch reads a request against
	// these declarations; a caller holding the sandbox reads the same
	// surface without one.
	Routes []*Route
	// Fail answers one failure with the project's own handler for it: it
	// reads route.Failure and calls the matching Handle* of
	// sandbox/internal/server/errors/. It is a field rather than a call
	// because a route package may not import sandbox/internal/generated/server/server
	// — that package imports every route — so this is how a generated
	// ReadBody, or the dispatch, reaches a file the project owns. Raise a
	// failure through routeio.Raise — or, from a handler, return one built
	// by routeio.Fail — rather than calling this directly.
	Fail func(route *Route) error
}

// ServeProps describes one run of the http server: the address to listen on
// — host:port (":8080"), a bare port ("8080"), or a range of ports tried in
// turn, with or without a host ("3000:4000", "127.0.0.1:3000:4000") —
// the two timeouts, in milliseconds, a request and a response are held to, and
// how long the requests in flight get to finish once the process is asked to
// stop (0 waits for them).
type ServeProps struct {
	Addr              string
	ReadTimeoutMs     int
	WriteTimeoutMs    int
	ShutdownTimeoutMs int
}

const (
	// StatusOk reports that the route did what it was asked to do.
	StatusOk = 200
	// StatusCreated reports that the route created what it was asked for.
	StatusCreated = 201
	// StatusNoContent reports success with nothing to send back.
	StatusNoContent = 204
	// StatusMovedPermanently sends the caller to Location for good.
	StatusMovedPermanently = 301
	// StatusFound sends the caller to Location this once.
	StatusFound = 302
	// StatusSeeOther sends the caller to Location with a GET, after a
	// form was handled.
	StatusSeeOther = 303
	// StatusNotModified reports that the caller's cached copy is current.
	StatusNotModified = 304
	// StatusTemporaryRedirect sends the caller to Location this once,
	// keeping its method.
	StatusTemporaryRedirect = 307
	// StatusPermanentRedirect sends the caller to Location for good,
	// keeping its method.
	StatusPermanentRedirect = 308
	// StatusBadRequest reports a request the dispatch could not bind: a
	// missing required field, an unparsable value, one out of range, or a
	// body the declared schema rejects.
	StatusBadRequest = 400
	// StatusUnauthorized reports a request that carries no valid
	// credentials.
	StatusUnauthorized = 401
	// StatusForbidden reports credentials that are valid and not enough.
	StatusForbidden = 403
	// StatusNotFound reports that no declared route matches the path.
	StatusNotFound = 404
	// StatusMethodNotAllowed reports a path a route matches under another
	// method.
	StatusMethodNotAllowed = 405
	// StatusConflict reports a well-formed request the current state refuses.
	StatusConflict = 409
	// StatusPayloadTooLarge reports a body longer than the route's
	// max-bytes.
	StatusPayloadTooLarge = 413
	// StatusUnsupportedMedia reports a content type the route does not
	// declare.
	StatusUnsupportedMedia = 415
	// StatusUnprocessable reports a well-formed request whose content
	// breaks a rule of the domain.
	StatusUnprocessable = 422
	// StatusTooManyRequests reports a caller over its rate.
	StatusTooManyRequests = 429
	// StatusFailure reports a well-formed request the route could not carry
	// out.
	StatusFailure = 500
	// StatusUnavailable reports a server that cannot answer right now.
	StatusUnavailable = 503
)
