package login

import (
	"github.com/mateusmoutinho/churrasco/sandbox/api"
	"github.com/mateusmoutinho/churrasco/sandbox/deps/serverdeps"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/generated/server/route"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/generated/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "login"
	self.AcceptMethods = []string{"POST"}
	self.Priority = 100
	self.ResponseType = "text/html"
	self.Segments = 2
	self.Pattern = "/admin/login"
	self.Category = "Backoffice"
	self.Help = "Signs a backoffice user in and sets the session cookie"
	self.LongDescription = "The username field takes a username or an email. A match sets the session cookie and redirects to /admin/home; anything else answers the login page under a 401. After 20 failed sign-ins from one client ip, or 10 on one login, in 15 minutes, every attempt is answered the login page under a 429 with Retry-After, its password unchecked, until the 15 minutes pass."
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "AdminLogin",
			Start:       0,
			End:         1,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.EqualTrigger, Value: "/admin/login", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{}

	self.Body = api.RouteBody{
		Type:        "form",
		Required:    true,
		MaxBytes:    1048576,
		ContentType: "application/x-www-form-urlencoded",
		Schema:      BodySchema,
	}

	self.ReadBody = func(bound *api.Route) (any, error) {
		return ReadBody(sandbox, bound)
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
