package start_server

// Entries is every value this command reads off a command line, one field per
// entry of its command.yaml: FullCommand, the whole command line, then one per
// entry of `args` and one per entry of `flags`, each tagged with the id the
// generic CommandHandler fills it by. InternalPureHandler is handed one,
// already filled.
// Generated by `agnos build` — do not edit by hand.
type Entries struct {
	FullCommand       []string `id:"FullCommand"`
	Command           string   `id:"Command"`
	Addr              string   `id:"Addr"`
	ReadTimeoutMs     int      `id:"ReadTimeoutMs"`
	WriteTimeoutMs    int      `id:"WriteTimeoutMs"`
	ShutdownTimeoutMs int      `id:"ShutdownTimeoutMs"`
}
