package client_ip

import (
	"github.com/mateusmoutinho/churrasco/sandbox/api"
	"github.com/mateusmoutinho/churrasco/sandbox/deps/serverdeps"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/generated/server/route"
	"github.com/mateusmoutinho/churrasco/sandbox/internal/routeprops"
)

// NewRoute builds this route's declaration — a 1:1 image of its route.yaml —
// on the generic base of sandbox/internal/generated/server/route, and closes
// InternalPureHandler over the sandbox as the handler behind it. It is called
// once by sandbox/internal/generated/server/server/new.go, and what it returns is one
// entry of Server.Routes: the declaration alone, which the dispatch copies with
// api.BindRoute before binding a request onto it.
// Generated by `agnos build` — do not edit by hand; the logic
// lives in InternalPureHandler.go.
func NewRoute(sandbox *api.Sandbox) *api.Route {
	self := route.NewRoute(sandbox)

	self.Name = "client_ip"
	self.AcceptMethods = []string{"ANY"}
	self.Priority = 7
	self.ResponseType = "text/plain"
	self.Segments = 0
	self.Pattern = "/*"
	self.Category = "Middleware"
	self.Help = "Works out the client ip every route after it reads, from the connection or the reverse proxy in front"
	self.LongDescription = ""
	self.Examples = []string{}
	self.Hidden = false

	self.Paths = []api.Path{
		{
			Id:          "Route",
			Start:       0,
			End:         -1,
			Type:        api.StringPath,
			Description: "",
			Trigger:     api.Trigger{Exist: true, Type: api.PrefixTrigger, Value: "/", Negate: false, IgnoreCase: false},
		},
	}

	self.Parameters = []api.Parameter{
		{
			Id:          "XClientIp",
			Key:         "x-client-ip",
			Fonts:       []api.ParameterFont{api.HeaderParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the ip of the connection, set by the server and never by the client",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
		{
			Id:          "XForwardedFor",
			Key:         "x-forwarded-for",
			Fonts:       []api.ParameterFont{api.HeaderParam},
			Required:    false,
			Type:        api.StringType,
			Default:     "",
			HasDefault:  false,
			Description: "the client chain a reverse proxy appended to, read only with --allow-x-forwarded-for",
			Trigger:     api.Trigger{Exist: false, Type: api.EqualTrigger, Value: "", Negate: false, IgnoreCase: false},
		},
	}

	self.Body = api.RouteBody{
		Type:        "none",
		Required:    false,
		MaxBytes:    1048576,
		ContentType: "",
		Schema:      "",
	}

	self.InternalPureHandler = func(props *routeprops.RouteProps, entries *Entries, response *serverdeps.Response) error {
		return InternalPureHandler(sandbox, props, entries, response)
	}

	return self
}
