package estatisticas

import (
	api "github.com/mateusmoutinho/churrasco/sandbox/api"
	database "github.com/mateusmoutinho/churrasco/sandbox/deps/database"
)

// This file is generated by `agnos build` from specs.yaml — do not edit by hand.
// A query specs.yaml cannot describe goes in methods_custom.go, which no build
// reads and no build rewrites.

// VisitaItem is one stored visita record: its permanent id and every
// plain field the declaration gives it.
type VisitaItem struct {
	Id       int64
	Criadoem int64
}

// VisitaNew is one insert into visita: the fields a new record carries.
type VisitaNew struct {
	Criadoem int64
}

// VisitaFiltrage narrows a ListVisita. Every plain field is here, because
// only a `key` field is indexed and this is the one way to reach the rest. A
// zero value turns its own filter off.
type VisitaFiltrage struct {
	CriadoemMin int64
	CriadoemMax int64
}

// CalculoItem is one stored calculo record: its permanent id and every
// plain field the declaration gives it.
type CalculoItem struct {
	Id       int64
	Adultos  int64
	Criancas int64
	Carneg   int64
	Cervejas int64
	Criadoem int64
}

// CalculoNew is one insert into calculo: the fields a new record carries.
type CalculoNew struct {
	Adultos  int64
	Criancas int64
	Carneg   int64
	Cervejas int64
	Criadoem int64
}

// CalculoFiltrage narrows a ListCalculo. Every plain field is here, because
// only a `key` field is indexed and this is the one way to reach the rest. A
// zero value turns its own filter off.
type CalculoFiltrage struct {
	AdultosMin  int64
	AdultosMax  int64
	CriancasMin int64
	CriancasMax int64
	CarnegMin   int64
	CarnegMax   int64
	CervejasMin int64
	CervejasMax int64
	CriadoemMin int64
	CriadoemMax int64
}

// Estatisticas is the estatisticas database: the handle it was built over and one
// function field per generated method. Building one is free — it touches no
// key and creates nothing until the first record is written — so whoever needs
// it calls New on the spot instead of reading it off the Sandbox.
type Estatisticas struct {
	sandbox *api.Sandbox
	handle  database.DatabaseHandle

	// AddVisita inserts one visita record.
	AddVisita func(props VisitaNew) (VisitaItem, error)
	// FindVisitaById reads one visita record by its permanent id.
	FindVisitaById func(id int64) (VisitaItem, bool)
	// ListVisita reads every visita record the filtrage keeps.
	ListVisita func(filtrage VisitaFiltrage) ([]VisitaItem, error)
	// PageVisita reads one page of visita records, counted from 1.
	PageVisita func(position int, chunk int) ([]VisitaItem, error)
	// CountVisita is how many visita records are live.
	CountVisita func() (int, error)
	// UpdateVisitaCriadoem writes a new criadoem on one visita record.
	UpdateVisitaCriadoem func(id int64, value int64) error
	// RemoveVisita deletes one visita record and everything nested under it.
	RemoveVisita func(id int64) error
	// AddCalculo inserts one calculo record.
	AddCalculo func(props CalculoNew) (CalculoItem, error)
	// FindCalculoById reads one calculo record by its permanent id.
	FindCalculoById func(id int64) (CalculoItem, bool)
	// ListCalculo reads every calculo record the filtrage keeps.
	ListCalculo func(filtrage CalculoFiltrage) ([]CalculoItem, error)
	// PageCalculo reads one page of calculo records, counted from 1.
	PageCalculo func(position int, chunk int) ([]CalculoItem, error)
	// CountCalculo is how many calculo records are live.
	CountCalculo func() (int, error)
	// UpdateCalculoAdultos writes a new adultos on one calculo record.
	UpdateCalculoAdultos func(id int64, value int64) error
	// UpdateCalculoCriancas writes a new criancas on one calculo record.
	UpdateCalculoCriancas func(id int64, value int64) error
	// UpdateCalculoCarneg writes a new carneg on one calculo record.
	UpdateCalculoCarneg func(id int64, value int64) error
	// UpdateCalculoCervejas writes a new cervejas on one calculo record.
	UpdateCalculoCervejas func(id int64, value int64) error
	// UpdateCalculoCriadoem writes a new criadoem on one calculo record.
	UpdateCalculoCriadoem func(id int64, value int64) error
	// RemoveCalculo deletes one calculo record and everything nested under it.
	RemoveCalculo func(id int64) error
}
