package estatisticas

import (
	api "github.com/mateusmoutinho/churrasco/sandbox/api"
	database "github.com/mateusmoutinho/churrasco/sandbox/deps/database"
	databaseio "github.com/mateusmoutinho/churrasco/sandbox/internal/generated/databaseio"
)

// This file is generated by `agnos build` from specs.yaml — do not edit by hand.
//
// Every function takes the sandbox first, the way every function of
// sandbox/internal/ does. A search answers (record, false) when there is
// nothing to find and a write answers an error when something went wrong; no
// stored value is ever asserted into a type without checking, so a malformed
// record is an error rather than a panic.

// AddVisita inserts one visita record.
func AddVisita(sandbox *api.Sandbox, self *Estatisticas, props VisitaNew) (VisitaItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "visita")
	if err != nil {
		return VisitaItem{}, err
	}
	item, failure := schema.NewItem(newVisitaFields(props))
	if failure != nil {
		return VisitaItem{}, databaseio.Fail(sandbox, failure)
	}
	return buildVisitaItem(sandbox, item)
}

// FindVisitaById reads one visita record by its permanent id.
func FindVisitaById(sandbox *api.Sandbox, self *Estatisticas, id int64) (VisitaItem, bool) {
	schema, err := databaseio.Schema(sandbox, self.handle, "visita")
	if err != nil {
		sandbox.Deps.Std.Log("FindVisitaById: %s \n", err.Error())
		return VisitaItem{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return VisitaItem{}, false
	}
	built, err := buildVisitaItem(sandbox, item)
	if err != nil {
		sandbox.Deps.Std.Log("FindVisitaById: %s \n", err.Error())
		return VisitaItem{}, false
	}
	return built, true
}

// ListVisita reads every visita record the filtrage keeps.
func ListVisita(sandbox *api.Sandbox, self *Estatisticas, filtrage VisitaFiltrage) ([]VisitaItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "visita")
	if err != nil {
		return nil, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	kept := []VisitaItem{}
	for _, item := range items {
		built, err := buildVisitaItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		if !matchVisita(sandbox, built, filtrage) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
}

// PageVisita reads one page of visita records, counted from 1.
func PageVisita(sandbox *api.Sandbox, self *Estatisticas, position int, chunk int) ([]VisitaItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "visita")
	if err != nil {
		return nil, err
	}
	items, failure := schema.List(position, chunk)
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	page := []VisitaItem{}
	for _, item := range items {
		built, err := buildVisitaItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
}

// CountVisita is how many visita records are live.
func CountVisita(sandbox *api.Sandbox, self *Estatisticas) (int, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "visita")
	if err != nil {
		return 0, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return 0, databaseio.Fail(sandbox, failure)
	}
	return len(items), nil
}

// UpdateVisitaCriadoem writes a new criadoem on one visita record.
func UpdateVisitaCriadoem(sandbox *api.Sandbox, self *Estatisticas, id int64, value int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "visita")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("visita %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("criadoem", value))
}

// RemoveVisita deletes one visita record and everything nested under it.
func RemoveVisita(sandbox *api.Sandbox, self *Estatisticas, id int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "visita")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("visita %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Remove())
}

// AddCalculo inserts one calculo record.
func AddCalculo(sandbox *api.Sandbox, self *Estatisticas, props CalculoNew) (CalculoItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return CalculoItem{}, err
	}
	item, failure := schema.NewItem(newCalculoFields(props))
	if failure != nil {
		return CalculoItem{}, databaseio.Fail(sandbox, failure)
	}
	return buildCalculoItem(sandbox, item)
}

// FindCalculoById reads one calculo record by its permanent id.
func FindCalculoById(sandbox *api.Sandbox, self *Estatisticas, id int64) (CalculoItem, bool) {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		sandbox.Deps.Std.Log("FindCalculoById: %s \n", err.Error())
		return CalculoItem{}, false
	}
	item, ok := schema.FindById(id)
	if !ok {
		return CalculoItem{}, false
	}
	built, err := buildCalculoItem(sandbox, item)
	if err != nil {
		sandbox.Deps.Std.Log("FindCalculoById: %s \n", err.Error())
		return CalculoItem{}, false
	}
	return built, true
}

// ListCalculo reads every calculo record the filtrage keeps.
func ListCalculo(sandbox *api.Sandbox, self *Estatisticas, filtrage CalculoFiltrage) ([]CalculoItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return nil, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	kept := []CalculoItem{}
	for _, item := range items {
		built, err := buildCalculoItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		if !matchCalculo(sandbox, built, filtrage) {
			continue
		}
		kept = append(kept, built)
	}
	return kept, nil
}

// PageCalculo reads one page of calculo records, counted from 1.
func PageCalculo(sandbox *api.Sandbox, self *Estatisticas, position int, chunk int) ([]CalculoItem, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return nil, err
	}
	items, failure := schema.List(position, chunk)
	if failure != nil {
		return nil, databaseio.Fail(sandbox, failure)
	}
	page := []CalculoItem{}
	for _, item := range items {
		built, err := buildCalculoItem(sandbox, item)
		if err != nil {
			return nil, err
		}
		page = append(page, built)
	}
	return page, nil
}

// CountCalculo is how many calculo records are live.
func CountCalculo(sandbox *api.Sandbox, self *Estatisticas) (int, error) {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return 0, err
	}
	items, failure := schema.ListAll()
	if failure != nil {
		return 0, databaseio.Fail(sandbox, failure)
	}
	return len(items), nil
}

// UpdateCalculoAdultos writes a new adultos on one calculo record.
func UpdateCalculoAdultos(sandbox *api.Sandbox, self *Estatisticas, id int64, value int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("calculo %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("adultos", value))
}

// UpdateCalculoCriancas writes a new criancas on one calculo record.
func UpdateCalculoCriancas(sandbox *api.Sandbox, self *Estatisticas, id int64, value int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("calculo %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("criancas", value))
}

// UpdateCalculoCarneg writes a new carneg on one calculo record.
func UpdateCalculoCarneg(sandbox *api.Sandbox, self *Estatisticas, id int64, value int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("calculo %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("carneg", value))
}

// UpdateCalculoCervejas writes a new cervejas on one calculo record.
func UpdateCalculoCervejas(sandbox *api.Sandbox, self *Estatisticas, id int64, value int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("calculo %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("cervejas", value))
}

// UpdateCalculoCriadoem writes a new criadoem on one calculo record.
func UpdateCalculoCriadoem(sandbox *api.Sandbox, self *Estatisticas, id int64, value int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("calculo %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Update("criadoem", value))
}

// RemoveCalculo deletes one calculo record and everything nested under it.
func RemoveCalculo(sandbox *api.Sandbox, self *Estatisticas, id int64) error {
	schema, err := databaseio.Schema(sandbox, self.handle, "calculo")
	if err != nil {
		return err
	}
	item, ok := schema.FindById(id)
	if !ok {
		return sandbox.Deps.Std.Errorf("calculo %d not found", id)
	}
	return databaseio.Fail(sandbox, item.Remove())
}

// newVisitaFields is one insert into visita as the stored field map.
func newVisitaFields(props VisitaNew) map[string]any {
	return map[string]any{
		"criadoem": props.Criadoem,
	}
}

// buildVisitaItem reads one stored visita record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildVisitaItem(sandbox *api.Sandbox, item database.SchemaItem) (VisitaItem, error) {
	built := VisitaItem{Id: item.Id}

	criadoem_value, err := databaseio.ReadInt(sandbox, item, "criadoem")
	if err != nil {
		return built, err
	}
	built.Criadoem = criadoem_value

	return built, nil
}

// matchVisita is one VisitaFiltrage applied to one record. A zero value
// never filters, so an empty filtrage keeps everything.
func matchVisita(sandbox *api.Sandbox, item VisitaItem, filtrage VisitaFiltrage) bool {
	if !databaseio.IntInRange(item.Criadoem, filtrage.CriadoemMin, filtrage.CriadoemMax) {
		return false
	}
	return true
}

// newCalculoFields is one insert into calculo as the stored field map.
func newCalculoFields(props CalculoNew) map[string]any {
	return map[string]any{
		"adultos":  props.Adultos,
		"criancas": props.Criancas,
		"carneg":   props.Carneg,
		"cervejas": props.Cervejas,
		"criadoem": props.Criadoem,
	}
}

// buildCalculoItem reads one stored calculo record back into its Go form.
// Every conversion is checked, so a value of the wrong type is an error rather
// than a panic.
func buildCalculoItem(sandbox *api.Sandbox, item database.SchemaItem) (CalculoItem, error) {
	built := CalculoItem{Id: item.Id}

	adultos_value, err := databaseio.ReadInt(sandbox, item, "adultos")
	if err != nil {
		return built, err
	}
	built.Adultos = adultos_value

	criancas_value, err := databaseio.ReadInt(sandbox, item, "criancas")
	if err != nil {
		return built, err
	}
	built.Criancas = criancas_value

	carneg_value, err := databaseio.ReadInt(sandbox, item, "carneg")
	if err != nil {
		return built, err
	}
	built.Carneg = carneg_value

	cervejas_value, err := databaseio.ReadInt(sandbox, item, "cervejas")
	if err != nil {
		return built, err
	}
	built.Cervejas = cervejas_value

	criadoem_value, err := databaseio.ReadInt(sandbox, item, "criadoem")
	if err != nil {
		return built, err
	}
	built.Criadoem = criadoem_value

	return built, nil
}

// matchCalculo is one CalculoFiltrage applied to one record. A zero value
// never filters, so an empty filtrage keeps everything.
func matchCalculo(sandbox *api.Sandbox, item CalculoItem, filtrage CalculoFiltrage) bool {
	if !databaseio.IntInRange(item.Adultos, filtrage.AdultosMin, filtrage.AdultosMax) {
		return false
	}
	if !databaseio.IntInRange(item.Criancas, filtrage.CriancasMin, filtrage.CriancasMax) {
		return false
	}
	if !databaseio.IntInRange(item.Carneg, filtrage.CarnegMin, filtrage.CarnegMax) {
		return false
	}
	if !databaseio.IntInRange(item.Cervejas, filtrage.CervejasMin, filtrage.CervejasMax) {
		return false
	}
	if !databaseio.IntInRange(item.Criadoem, filtrage.CriadoemMin, filtrage.CriadoemMax) {
		return false
	}
	return true
}
