package estatisticas

import (
	api "github.com/mateusmoutinho/churrasco/sandbox/api"
	database "github.com/mateusmoutinho/churrasco/sandbox/deps/database"
)

// New builds the estatisticas database from the Props its specs.yaml declares and
// closes every method of methods.go over it. It touches no key: a database is
// a handle over a prefix, so building one creates nothing until the first
// record is written.
//
// Generated by `agnos build` — do not edit by hand.
func New(sandbox *api.Sandbox) *Estatisticas {
	props := database.Props{
		Path: "estatisticas",
		Schemas: []database.Schema{
			{
				Name: "visita",
				Itens: []database.Item{
					{Name: "criadoem", Type: database.Int, Required: true},
				},
			},
			{
				Name: "calculo",
				Itens: []database.Item{
					{Name: "adultos", Type: database.Int, Required: true},
					{Name: "criancas", Type: database.Int},
					{Name: "carneg", Type: database.Int},
					{Name: "cervejas", Type: database.Int},
					{Name: "criadoem", Type: database.Int, Required: true},
				},
			},
		},
	}

	self := Estatisticas{sandbox: sandbox}
	self.handle = sandbox.Deps.Database.Databases.New(props)

	self.AddVisita = func(props VisitaNew) (VisitaItem, error) {
		return AddVisita(self.sandbox, &self, props)
	}
	self.FindVisitaById = func(id int64) (VisitaItem, bool) {
		return FindVisitaById(self.sandbox, &self, id)
	}
	self.ListVisita = func(filtrage VisitaFiltrage) ([]VisitaItem, error) {
		return ListVisita(self.sandbox, &self, filtrage)
	}
	self.PageVisita = func(position int, chunk int) ([]VisitaItem, error) {
		return PageVisita(self.sandbox, &self, position, chunk)
	}
	self.CountVisita = func() (int, error) {
		return CountVisita(self.sandbox, &self)
	}
	self.UpdateVisitaCriadoem = func(id int64, value int64) error {
		return UpdateVisitaCriadoem(self.sandbox, &self, id, value)
	}
	self.RemoveVisita = func(id int64) error {
		return RemoveVisita(self.sandbox, &self, id)
	}
	self.AddCalculo = func(props CalculoNew) (CalculoItem, error) {
		return AddCalculo(self.sandbox, &self, props)
	}
	self.FindCalculoById = func(id int64) (CalculoItem, bool) {
		return FindCalculoById(self.sandbox, &self, id)
	}
	self.ListCalculo = func(filtrage CalculoFiltrage) ([]CalculoItem, error) {
		return ListCalculo(self.sandbox, &self, filtrage)
	}
	self.PageCalculo = func(position int, chunk int) ([]CalculoItem, error) {
		return PageCalculo(self.sandbox, &self, position, chunk)
	}
	self.CountCalculo = func() (int, error) {
		return CountCalculo(self.sandbox, &self)
	}
	self.UpdateCalculoAdultos = func(id int64, value int64) error {
		return UpdateCalculoAdultos(self.sandbox, &self, id, value)
	}
	self.UpdateCalculoCriancas = func(id int64, value int64) error {
		return UpdateCalculoCriancas(self.sandbox, &self, id, value)
	}
	self.UpdateCalculoCarneg = func(id int64, value int64) error {
		return UpdateCalculoCarneg(self.sandbox, &self, id, value)
	}
	self.UpdateCalculoCervejas = func(id int64, value int64) error {
		return UpdateCalculoCervejas(self.sandbox, &self, id, value)
	}
	self.UpdateCalculoCriadoem = func(id int64, value int64) error {
		return UpdateCalculoCriadoem(self.sandbox, &self, id, value)
	}
	self.RemoveCalculo = func(id int64) error {
		return RemoveCalculo(self.sandbox, &self, id)
	}

	return &self
}
